#!/bin/bash

set -eo pipefail

if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "Set the GITHUB_TOKEN env variable."
  exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
  echo "Set the GITHUB_REPOSITORY env variable."
  exit 1
fi

URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

main() {
    echo "Start Main"
    printenv
  	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
    pr_nr=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    repo_name=$(jq --raw-output .name "$GITHUB_EVENT_PATH")
    app_name="$repo_name$pr_nr"
	  merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
	  echo "DEBUG -> action: $action merged: $merged pr_nr: $pr_nr repo_name: $repo_name app_name: $app_name"
    if [[ "$action" == "closed" ]] && [[ "$merged" == "true" ]]; then

      echo "Bingo - PR is closed or merged. Let's get rid of the helm"
    fi
}

main "$@"