#!/bin/bash

set -eo pipefail

if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "Set the GITHUB_TOKEN env variable."
  exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
  echo "Set the GITHUB_REPOSITORY env variable."
  exit 1
fi

URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

main() {
    echo "Start Main"
    printenv
  	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
	  merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
	  echo "DEBUG -> action: $action merged: $merged"

    if [[ "$action" == "closed" ]] && [[ "$merged" == "true" ]]; then
      echo "Bingo - PR is closed or merged. Let's get rid of the helm"
    fi
}

main "$@"