#!/bin/bash

set -eo pipefail

if [[ -z "$GITHUB_TOKEN" ]]; then
  echo "Set the GITHUB_TOKEN env variable."
  exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
  echo "Set the GITHUB_REPOSITORY env variable."
  exit 1
fi

if [[ -z "$GCLOUD_ZONE" ]]; then
  echo "Set the GCLOUD_ZONE env variable."
  exit 1
fi

if [[ -z "$GCLOUD_CLUSTER" ]]; then
  echo "Set the GCLOUD_CLUSTER env variable."
  exit 1
fi

if [[ -z "$GCLOUD_PROJECT" ]]; then
  echo "Set the CLOUD_PROJECT env variable."
  exit 1
fi


URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

main() {
    echo "Start Main"
    echo "conntect to dev cluster"
  	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
    pr_nr=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    repo_name=$(jq --raw-output .repository.name "$GITHUB_EVENT_PATH")
	  merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
    chart_name="pr-$pr_nr-$repo_name"
	  echo "DEBUG -> action: $action merged: $merged pr_nr: $pr_nr repo_name: $repo_name chart_name: $chart_name"
    if [[ "$action" == "closed" ]] && [[ "$merged" == "true" ]]; then 
      echo "Bingo - PR is closed or merged. Let's get rid of the helm"
      gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT
      helm delete $chart_name --purge
    fi
}

main "$@"